package io.github.aihub.bootstrap.config;
import io.github.aihub.auth.*;import io.github.aihub.system.repo.*;import io.github.aihub.system.entity.*;import org.springframework.beans.factory.annotation.*;import org.springframework.context.annotation.*;import org.springframework.http.*;import org.springframework.security.authentication.*;import org.springframework.security.config.annotation.method.configuration.*;import org.springframework.security.config.annotation.web.builders.*;import org.springframework.security.config.http.*;import org.springframework.security.core.authority.*;import org.springframework.security.crypto.bcrypt.*;import org.springframework.security.crypto.password.*;import org.springframework.security.web.*;import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;import org.springframework.web.filter.OncePerRequestFilter;import org.springframework.web.cors.*;import jakarta.servlet.*;import jakarta.servlet.http.*;import java.io.*;
@Configuration @EnableMethodSecurity public class SecurityConfig{
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean JwtService jwt(@Value("${aihub.jwt.secret}")String secret){return new JwtService(secret);}
 @Bean SecurityFilterChain chain(HttpSecurity h,JwtService jwt)throws Exception{return h.csrf(c->c.disable()).cors(c->c.configurationSource(req->{var x=new CorsConfiguration();x.addAllowedOriginPattern("*");x.addAllowedHeader("*");x.addAllowedMethod("*");return x;})).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/v1/auth/**","/actuator/**").permitAll().anyRequest().authenticated()).addFilterBefore(new JwtFilter(jwt),UsernamePasswordAuthenticationFilter.class).build();}
 static class JwtFilter extends OncePerRequestFilter{
  private final JwtService jwt;JwtFilter(JwtService j){jwt=j;}
  protected void doFilterInternal(HttpServletRequest r,HttpServletResponse s,FilterChain c)throws ServletException,IOException{String h=r.getHeader("Authorization");if(h!=null&&h.startsWith("Bearer ")){try{var claims=jwt.parse(h.substring(7)).getPayload();var auth=new UsernamePasswordAuthenticationToken(claims.getSubject(),null,((java.util.List<?>)claims.get("roles")).stream().map(x->new SimpleGrantedAuthority("ROLE_"+x)).toList());org.springframework.security.core.context.SecurityContextHolder.getContext().setAuthentication(auth);}catch(Exception ignored){}}c.doFilter(r,s,c);}
 }
}