package io.github.aihub.provider.provider;
import io.github.aihub.provider.dto.*;import io.github.aihub.provider.spi.*;import io.github.aihub.provider.stream.*;import com.fasterxml.jackson.databind.*;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.stereotype.Component;import org.springframework.web.reactive.function.client.WebClient;import reactor.core.publisher.Flux;
@Component
public class OpenAICompatibleProvider implements AIProvider{
 private final WebClient client; private final ObjectMapper json;
 public OpenAICompatibleProvider(@Value("${aihub.providers.openai.base-url:https://api.openai.com/v1}") String base,@Value("${aihub.providers.openai.api-key:}") String key,ObjectMapper json){this.client=WebClient.builder().baseUrl(base.replaceAll("/+$","")).defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+key).build();this.json=json;}
 public String name(){return "openai-compatible";}
 public boolean supports(String m){return m!=null&&(m.startsWith("gpt-")||m.startsWith("openai:"));}
 private String model(String m){return m.startsWith("openai:")?m.substring(7):m;}
 private Map<String,Object> body(ProviderChatRequest r,boolean stream){Map<String,Object>b=new LinkedHashMap<>();b.put("model",model(r.model()));b.put("messages",r.messages().stream().map(x->Map.of("role",x.role(),"content",x.content())).toList());b.put("stream",stream);if(r.temperature()!=null)b.put("temperature",r.temperature());if(r.maxTokens()!=null)b.put("max_tokens",r.maxTokens());return b;}
 public ProviderChatResponse chat(ProviderChatRequest r){JsonNode root=client.post().uri("/chat/completions").contentType(MediaType.APPLICATION_JSON).bodyValue(body(r,false)).retrieve().bodyToMono(JsonNode.class).block();if(root==null)throw new IllegalStateException("Empty provider response");JsonNode c=root.path("choices").path(0);return new ProviderChatResponse(name(),root.path("model").asText(model(r.model())),c.path("message").path("content").asText(""),c.path("finish_reason").asText(null));}
 public Flux<ProviderStreamEvent> stream(ProviderChatRequest r){String m=model(r.model());return client.post().uri("/chat/completions").contentType(MediaType.APPLICATION_JSON).accept(MediaType.TEXT_EVENT_STREAM).bodyValue(body(r,true)).retrieve().bodyToFlux(String.class).flatMap(s->{String p=s.startsWith("data:")?s.substring(5).trim():s.trim();if(p.equals("[DONE]"))return Flux.just(new ProviderStreamEvent("done",name(),m,null,"stop"));try{JsonNode c=json.readTree(p).path("choices").path(0);String d=c.path("delta").path("content").asText("");String f=c.path("finish_reason").asText(null);if(f!=null)return Flux.just(new ProviderStreamEvent("done",name(),m,null,f));return d.isEmpty()?Flux.empty():Flux.just(new ProviderStreamEvent("delta",name(),m,d,null));}catch(Exception e){return Flux.just(new ProviderStreamEvent("error",name(),m,"Invalid SSE payload",null));}}).takeUntil(e->"done".equals(e.type())||"error".equals(e.type()));}
}