import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import Login from './Login';
import Chat from './Chat';
import './styles.css';

function Dashboard({ onLogout, onChat }: { onLogout: () => void; onChat: () => void }) { return <div className="app"><aside><div className="brand">AI<span>Hub</span></div><nav><a className="active">⌂ Dashboard</a><a onClick={onChat}>✦ AI Chat</a><a>◫ Conversations</a><a>◈ Models</a><a>⚙ Settings</a></nav><div className="user"><div className="avatar">A</div><div><b>AIHub User</b><small>Tenant {localStorage.getItem('aihub_tenant_id') || '1'}</small></div><button className="logout" onClick={onLogout}>×</button></div></aside><main><header><div><p className="eyebrow">AI PLATFORM</p><h1>Welcome to AIHub</h1><p className="muted">One place to manage models, conversations and AI providers.</p></div><button onClick={onChat}>＋ New Chat</button></header><section className="grid"><article><small>ACTIVE MODELS</small><strong>1</strong><p>OpenAI-compatible provider</p></article><article><small>CONVERSATIONS</small><strong>0</strong><p>Start your first conversation</p></article><article><small>API STATUS</small><strong className="ok">● Online</strong><p>Backend services are ready</p></article></section><section className="hero"><div><p className="eyebrow">START HERE</p><h2>Talk to your AI</h2><p className="muted">Authentication and tenant context are connected. Start a streaming conversation with the configured model.</p><button className="primary" onClick={onChat}>Start a conversation →</button></div><div className="orb">✦</div></section></main></div> }

function App(){ const [authenticated,setAuthenticated]=useState(Boolean(localStorage.getItem('aihub_token'))); const [chatOpen,setChatOpen]=useState(false); function logout(){localStorage.removeItem('aihub_token');setAuthenticated(false);setChatOpen(false)} if(!authenticated)return <Login onLogin={()=>setAuthenticated(true)}/>; if(chatOpen)return <Chat onBack={()=>setChatOpen(false)}/>; return <Dashboard onLogout={logout} onChat={()=>setChatOpen(true)}/> }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
