services:
  - type: web
    name: aihub-web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: aihub-web
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        value: https://aihub-server.onrender.com
